# Generated by Django 3.2.5 on 2021-08-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
