# Generated by Django 3.2.5 on 2021-08-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0002_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(related_name='dishes', to='restaurants_app.Dish'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='restaurants_app.Menu'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(related_name='catrgories', to='restaurants_app.Menu'),
        ),
    ]
