# Generated by Django 3.2.5 on 2021-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_app', '0003_auto_20210806_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ManyToManyField(related_name='menues', to='restaurants_app.Menu'),
        ),
    ]
